name: Ronin Ecosystem Validator

on:
  pull_request_target:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  post_merge:
    name: "Ronin Buddy"
    uses: './.github/workflows/ci.yml'
    secrets: inherit
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}